# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5.0.2
_src_path: https://github.com/epics-containers/services-template-helm
athena_services:
- rabbitmq
- blueapi
- nexus
auth_enabled: true
cluster_name: pollux
cluster_namespace: p46-beamline
description: p46 IOC Instances and Services
domain: p46
gateway: true
git_platform: github.com
instrument: p46
location: bl46p
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
numtracker_enabled: true
