apiVersion: v2
name: p46-rabbitmq
description: RabbitMQ instance for DAQ services on p46
version: 16.0.5

# When we deploy with the edge-containers-cli we override this on the command line.
# Direct deployment with Helm will use the default beta value.
appVersion: 0.0.1b1

type: application

dependencies:
  - name: rabbitmq
    version: 16.0.13
    repository: oci://registry-1.docker.io/bitnamicharts
