rabbitmq:
  authentication:
    user:
      value: admin
    existingSecret: rabbitmq-secrets
    password:
      secretKey: rabbitmq-password
    erlangCookie:
      secretKey: rabbitmq-erlang-cookie
  plugins:
  - rabbitmq_jms_topic_exchange
  - rabbitmq_stomp
  rbac:
    create: false
  serviceAccount:
    create: false
  service:
    type: LoadBalancer
    loadBalancerIP: 172.23.168.212
    extraPorts:
      - name: stomp
        port: 61613
        targetPort: stomp
        containerPort: 61613
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
      ephemeral-storage: 50Mi
    limits:
      cpu: 750m
      memory: 1536Mi
      ephemeral-storage: 2Gi
