apiVersion: v2
name: p46-blueapi
description: blueapi deployed for p46
version: 1.0.0

# When we deploy with the edge-containers-cli we override this on the command line.
# Direct deployment with Helm will use the default beta value.
appVersion: 0.0.1b1

type: application

dependencies:
  - name: blueapi
    version: "1.6.2-a2"
    repository: "oci://ghcr.io/diamondlightsource/charts"

  - name: oauth2-proxy
    alias: oauth2
    repository: https://oauth2-proxy.github.io/manifests
    version: 8.3.1
