epics-gateways:
  # developer image for debugging no longer needed - defaults to helm chart version
  # image: ghcr.io/epics-containers/epics-gateways-developer:2026.3.18

  # use ixxdetector account for your beamline
  securityContext:
    runAsUser: 37890
    runAsGroup: 37890

  # affinity chooses which servers to run on
  # Accelerator must set this for CIAs, Beamlines don't need it
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - p46

  # tolerations allow us to run on a tainted server
  # Accelerator must set this for CIAs, Beamlines don't need it
  tolerations:
    - key: beamline
      operator: Equal
      value: p46
      effect: NoSchedule
    - key: location
      operator: Equal
      value: p46
      effect: NoSchedule
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule
