apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.proxy.name }}-nginx
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location / {
          proxy_pass http://{{ .Values.proxy.target.host }}:{{ .Values.proxy.target.port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
