apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ include "bl46-panda-web-gui.fullname" . }}-slice
  labels:
    kubernetes.io/service-name: {{ .Values.service.name }}
addressType: IPv4
ports:
{{- range .Values.service.ports }}
  - name: {{ .name }}
    protocol: TCP
    port: {{ .targetPort }}
{{- end }}
endpoints:
{{- range .Values.service.endpoints }}
  - addresses:
      - {{ .ip | quote }}
    conditions:
      ready: true
{{- end }}
