apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.service.name }}
subsets:
  - addresses:
  {{- range .Values.service.endpoints }}
      - ip: {{ .ip }}
  {{- end }}
    ports:
  {{- range .Values.service.ports }}
      - name: {{ .name }}
        port: {{ .targetPort }}
  {{- end }}
