apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.name }}
spec:
  ports:
    - port: {{ .Values.proxy.servicePort }}
      targetPort: {{ .Values.proxy.servicePort }}
  selector:
    app: {{ .Values.proxy.name }}
