apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  clusterIP: None
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
