apiVersion: v2
name: p46-panda-web-gui
description: Nginx-based reverse proxy exposing the test rig's internal panda web GUI to the outside world


type: application

version: 19.0.0

dependencies:
  - name: nginx
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 20.0.2
