nginx:
  serverBlock: |-
    server {
      listen 0.0.0.0:8080 ipv6only=off;

      # CHANGE THIS TO YOUR SERVER'S NAME
      server_name panda;

      location / {
          proxy_pass http://192.168.250.18:8008;

          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Proto $scheme;

          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
      }
    }
  ingress:
    enabled: true
    hostName: bl46p-mo-panda-01.diamond.ac.uk
    pathType: Exact
  networkPolicy:
    enabled: false
  nodeSelector:
    kubernetes.io/hostname: bl46p-ea-serv-01.diamond.ac.uk
  tolerations:
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule
    - key: beamline
      operator: Equal
      value: bl46p
      effect: NoSchedule
