nginx:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet # required when using hostNetwork

  nodeSelector:
    kubernetes.io/hostname: bl46p-ea-serv-01.diamond.ac.uk

  tolerations:
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule
    - key: beamline
      operator: Equal
      value: bl46p
      effect: NoSchedule


  containerPorts:
    http: 8080 # will serve proxied traffic from nginx
    https: 8443

  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
    targetPort:
      http: 8080
      https: 8443
    loadBalancerIP: 172.23.168.208 # hopefully matches bl46p-panda-01.diamond.ac.uk 
    externalTrafficPolicy: Local  # preserves source IP

  serverBlock: |
    server {
        listen 8080;
        # Redirect from root to /admin/
        
        location = / {
          return 301 /admin/;
        }
        
        location /control/ {
            proxy_pass http://192.168.250.18:8008/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /admin/ {
            proxy_pass http://192.168.250.18:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
