nginx:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet # required when using hostNetwork

  containerPorts:
    http: 8080 # will serve proxied traffic from nginx
    https: 8443

  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
    targetPort:
      http: 8080
      https: 8443
    loadBalancerIP: 203.0.113.50 # <-- your actual external static IP

  serverBlock: |
    server {
        listen 8080;

        location /control/ {
            proxy_pass http://192.168.250.18:8008/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /admin/ {
            proxy_pass http://192.168.250.18:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
