apiVersion: v2
name: numtracker
description: Central numtracker instance for numtracker.diamond.ac.uk

version: 0.1.6

appVersion: "0.1.6"

type: application

dependencies:
  - name: numtracker
    version: "1.0.2"
    repository: "file:///home/zoheb/workspace/numtracker/helm/numtracker"
