numtracker:
  numtracker:
    auth:
      enabled: true
      host: https://pxx-opa.diamond.ac.uk/
      admin: v1/data/diamond/policy/admin/configure_beamline
      access: v1/data/diamond/policy/session/write_to_beamline_visit
    storage:
      # Far bigger than required but the minimum PV size
      size: 20Mi
    rootTrackerDirectory: /trackers

  service:
    port: 8080
  ingress:
    enabled: false
    hosts:
      - host: numtracker.diamond.ac.uk
        paths:
          - path: /
            pathType: Prefix

  podSecurityContext:
    # Run as k8s-numtracker user and group so it can access /dls_sw
    runAsUser: 36120
    runAsGroup: 36120
  securityContext:
    privileged: false
  extraVolumes:
    # name can't include underscores
    - name: dls-sw
      hostPath:
        path: /dls_sw
        type: Directory
  extraVolumeMounts:
    - mountPath: /trackers/p38
      name: dls-sw
      mountPropagation: HostToContainer
      subPath: p38/software/gda_var
