# yaml-language-server: $schema=../.helm-shared/values.schema.json

# shared values for all services

global:
  domain: p46
  location: bl46p
  enabled: true

# shared settings for all IOC types
shared: &shared
  # hostNetwork
  # set to true for Channel Access to work outside of the cluster (or use a gateway)
  hostNetwork: true

  # affinity and tolerations to get the right nodes on pollux
  # running as ixxdetector account uid,gid gives access to /dls/ixx/data
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 37890
    runAsGroup: 37890

  # affinity chooses which servers to run on
  # Accelerator must set this for CIAs, Beamlines don't need it
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - bl46p

  # tolerations allow us to run on a tainted server
  # Accelerator must set this for CIAs, Beamlines don't need it
  tolerations:
    - key: beamline
      operator: Equal
      value: bl46p
      effect: NoSchedule
    - key: location
      operator: Equal
      value: bl46p
      effect: NoSchedule
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule

# shared settings for all ibek IOCs using the ioc-instance helm chart
ioc-instance:
  <<: *shared

# shared setting for all legacy IOCs using the dev-c7 helm chart
dev-c7:
  <<: *shared
