apiVersion: v2
name: p46-glazed
description: glazed deployment for p46
version: 0.1.0

appVersion: 0.1.0

type: application

dependencies:
  - name: glazed
    version: "add-helm"
    repository: "oci://ghcr.io/diamondlightsource/charts"