service:
  name: baremetal-service
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: http-alt
      port: 8008
      targetPort: 8008
  endpoints:
    - ip: 192.168.250.18

ingress:
  enabled: true
  className: nginx
  host: bl46p-panda-01.diamond.ac.uk
  path: /
  pathType: Prefix
  tls:
    enabled: false
    secretName: ""  # required if tls.enabled is true
