proxy:
  name: bl46-panda-web-gui
  replicaCount: 1
  target:
    host: 192.168.250.18
    port: 8008
  image: nginx:1.28
  servicePort: 80

ingress:
  enabled: true
  className: nginx
  host: bl46p-panda-01.diamond.ac.uk
  path: /
  pathType: Prefix
  tls:
    enabled: false
    secretName: "" # required if tls.enabled is true

