apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blueapi-secret
  namespace: p46-beamline
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgA325ckfHEtEi7sAWAaXkX76slYkWcuYaAIedtoHy+FSfCWifh4SwBUKvbS6Dl93gJGYhG4CltpnJAFTwBtHnS3hs6852kCoIptejiqkfs712i644npZMx1jfP1lqnzRXhBOdmCxtAD7m19U4MYBW0SnIUcXmoXTG9S2XG2IgF5KDIiU8sGMcEd4MbC+J26QseKHROqH+fkC7ShapAPYXxgradiCAh7N1OpwCGZA80P+OoE0znIqc09frqkvgPLabc91snt/GWsNupBP0QAM0p3/2yLgkV9O23hUrSaG3leNoQmcNsPLuDsf11ZVUNyAK8S23/xH7Hwhg6rBw09TOxP8pLJju3KWQ8jH5YICsON7QQgckOLZ/IXUNtAAsQJABvFWrPP09wB8LtnZH6xvZsXR0LV35B3uwxdJaacLzYco8r/eZ7oBLQFD49p1zdg8x7fAKVTUSzGcaZAbL9eFMW84LpZU9CfbEox+QlzwTD+S5Egz7hXRNjo8R9NBZrG6bzCZElpQzZ9HUIDqGbRkYLCoaeLzBQ9UvuheRmm2IBEzr5TsKnQHa/QGOt/6NGeHwQPUaKEJKQPfLZB/v3uIb8e0R/hKzk5OcTL79JUUwZNTTLdt17nt6jkGJLnK84F7JuYoUxYEn+UZ87C2KSxz2MELFu2RlH7Zm2PeOjpGUBFVood7AJmyxprh1W2LjRlMOqB4rkBvf3dEEU/yegbD4YoR2oHoDbqEzGw05XG/xhHtg==
