apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiled-storage-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
