blueapi:
  hostNetwork: true
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 100Mi
  nodeSelector:
    kubernetes.io/hostname: bl46p-ea-serv-01.diamond.ac.uk
  tolerations:
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule
    - key: beamline
      operator: Equal
      value: bl46p
      effect: NoSchedule
  ingress:
    create: true
    host: p46-blueapi.diamond.ac.uk
  extraEnvVars:
    - name: BEAMLINE
      value: p46

    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rabbitmq-password
          key: rabbitmq-password
  worker:
    env:
      sources:
      - kind: dodal
        module: dodal.beamlines.p46
      - kind: planFunctions
        module: i22_bluesky.plans
        # TODO: Make p46 plans repository
      - kind: planFunctions
        module: dls_bluesky_core.plans
      - kind: planFunctions
        module: dls_bluesky_core.stubs
      events:
        broadcast_status_events: False
    stomp:
      auth:
        username: p46
        password: ${RABBITMQ_PASSWORD}
      host: daq-rabbitmq
  
  InitContainer:
    scratch:
      root: /exports/mybeamline/p46/scratch/blueapi
      repositories:
        - name: dodal
          remote_url: https://github.com/DiamondLightSource/dodal.git
  scratchHostPath: /exports/mybeamline/p46/scratch/blueapi
