postgres:
  useDeployment: true

  image:
    registry: "docker.io"
    repository: postgres
    tag: 18.1-bookworm

  ## Database and user (user is optional, but recommended, as 'postgres' would be the only user otherwise)
  userDatabase:
    ## Optional existing secret with database name, user and password
    existingSecret: postgres-secret
    name: 
      ## Name of the user database
      secretKey: POSTGRES_DB
    password:
      ## Password of the database user
      secretKey: USER_PASS
    user:
      ## Database user with full access rights
      secretKey: USER_NAME

  ## Database configuration
  settings:
    ## Optional existing secret for the Postgrest superuser
    existingSecret: postgres-secret
    superuserPassword:
      secretKey: ADMIN_PASS


  storage:
    volumeName: db-postgres 
    keepPvc: true
    className: db-nvme-storage
    requestedSize: 8Gi
    accessModes:
      - ReadWriteOnce


  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsGroup: 999
    runAsUser: 999
    capabilities:
      drop:
        - ALL

  resources:
    limits:
      cpu: "0.5"
      memory: 1G
    requests:
      cpu: "0.5"
      memory: 1G

