nexus-file-converter:
  debug:
  # exposes Java debug listener on port 5005 on a ClusterIP, access it with
  # kubectl port-forward svc/daq-nexus-nexus-file-converter-debug-port 5005:5005 -n p46-beamline
    enabled: false
    suspend: false
  beamline: p46
  template:
    entry/:
      NX_class@: NXentry
      instrument/:
        NX_class@: NXinstrument
        name: p46

  nodeSelector:
    kubernetes.io/hostname: bl46p-ea-serv-01.diamond.ac.uk
  tolerations:
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule
    - key: beamline
      operator: Equal
      value: bl46p
      effect: NoSchedule

  volumes:
  - name: nexus-template
    configMap:
      name: nexus-template
      items:
      - key: template.yaml
        path: template.yaml
  - name: nexus-data
    hostPath:
      path: /exports/mybeamline/data/
      type: DirectoryOrCreate

  volumeMounts:
  - name: nexus-data
    mountPath: /exports/mybeamline/data/
    mountPropagation: HostToContainer
  - name: nexus-template
    mountPath: /templates

  application:
    server:
      port: 8084
    management:
      otlp:
        tracing:
          export:
            enabled: true
          endpoint: "http://opentelemetry-collector.tracing:4318/v1/traces"
    otlp:
      enabled: true
      endpoint: "http://opentelemetry-collector.tracing"
    micrometer:
      observations:
        annotations:
          enabled: true
    spring:
      profiles:
        active: rabbitmq
      rabbitmq:
        host: p46-rabbitmq-daq.diamond.ac.uk
        username: guest
        password: guest
    files:
      output:
        directory:
          staticDirectory: ""  # explicitly empty, get from StartDocument metadata
        devices:
          types:
            det: NX_DETECTOR
            sample_stage: NX_COLLECTION
            sample_stage.x: NX_POSITIONER
            sample_stage.theta: NX_POSITIONER
  securityContext:
    runAsUser: 37890 # p46-detector
    runAsGroup: 37890
